analyze_me/models/results.py
#analyze_me/models/results.py       2020/12/10   M.O
from analyze_me import db
from datetime import datetime
#from sqlalchemy.dialects import postgresql as pg

#フュージョンチェックデータベース
class FU_results(db.Model):
    __tablename__ = 'fu_results'
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    answers = db.Column(db.PickleType, nullable=True)
    #answers = db.Column(pg.ARRAY(db.String, dimensions=1), nullable=True)
    a_sum = db.Column(db.Integer, nullable=True)
    judge = db.Column(db.String(200), nullable=True)
    created_at = db.Column(db.DateTime)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', onupdate='CASCADE', ondelete='CASCADE'), nullable=False)

    @classmethod
    def from_args(cls, answers: [], a_sum: int, judge: str, user_id: int) -> object:
        instance = cls()
        instance.answers = answers
        instance.a_sum = a_sum
        instance.judge = judge
        instance.created_at = datetime.now()
        instance.user_id = user_id
        return instance

    def __repr__(self):
        return '<ID:{} answers:{} judge:{}>'.format(self.id, self.answers, self.judge)


#脱中心化チェックデータベース
class EQ_results(db.Model):
    __tablename__ = 'eq_results'
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    answers = db.Column(db.PickleType, nullable=True)
    a_sum = db.Column(db.Integer, nullable=True)
    judge = db.Column(db.String(200), nullable=True)
    created_at = db.Column(db.DateTime)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', onupdate='CASCADE', ondelete='CASCADE'), nullable=False)

    @classmethod
    def from_args(cls, answers: [], a_sum: int, judge: str, user_id: int) -> object:
        instance = cls()
        instance.answers = answers
        instance.a_sum = a_sum
        instance.judge = judge
        instance.created_at = datetime.now()
        instance.user_id = user_id
        return instance

    def __repr__(self):
        return '<ID:{} answers:{} judge:{}>'.format(self.id, self.answers, self.judge)


# CES-Dデータベース
class CES_results(db.Model):
    __tablename__ = 'ces_results'
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    answers = db.Column(db.PickleType, nullable=True)
    a_sum = db.Column(db.Integer, nullable=True)
    judge = db.Column(db.String(200), nullable=True)
    created_at = db.Column(db.DateTime)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', onupdate='CASCADE', ondelete='CASCADE'), nullable=False)

    @classmethod
    def from_args(cls, answers: [], a_sum: int, judge: str, user_id: int) -> object:
        instance = cls()
        instance.answers = answers
        instance.a_sum = a_sum
        instance.judge = judge
        instance.created_at = datetime.now()
        instance.user_id = user_id
        return instance

    def __repr__(self):
        return '<ID:{} answers:{} judge:{}>'.format(self.id, self.answers, self.judge)


#　POMSデータベース
class POM_results(db.Model):
    __tablename__ = 'pom_results'
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    answers = db.Column(db.PickleType, nullable=True)
    a_sum = db.Column(db.PickleType, nullable=True)
    #judge = db.Column(db.String(200), nullable=True)
    created_at = db.Column(db.DateTime)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', onupdate='CASCADE', ondelete='CASCADE'), nullable=False)

    @classmethod
    def from_args(cls, answers: [], a_sum: [], user_id: int) -> object:
        instance = cls()
        instance.answers = answers
        instance.a_sum = a_sum
        #instance.judge = judge
        instance.created_at = datetime.now()
        instance.user_id = user_id
        return instance

    def __repr__(self):
        return '<ID:{} answers:{} judge:{}>'.format(self.id, self.answers, self.a_sum)


#　TEGデータベース
class TEG_results(db.Model):
    __tablename__ = 'teg_results'
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    answers = db.Column(db.PickleType, nullable=True)
    a_sum = db.Column(db.PickleType, nullable=True)
    #judge = db.Column(db.String(200), nullable=True)
    created_at = db.Column(db.DateTime)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', onupdate='CASCADE', ondelete='CASCADE'), nullable=False)

    @classmethod
    def from_args(cls, answers: [], a_sum: [], user_id: int) -> object:
        instance = cls()
        instance.answers = answers
        instance.a_sum = a_sum
        #instance.judge = judge
        instance.created_at = datetime.now()
        instance.user_id = user_id
        return instance

    def __repr__(self):
        return '<ID:{} answers:{} judge:{}>'.format(self.id, self.answers, self.a_sum)

analyze_me/models/user.py
#analyze_me/models/user.py       2020/11/30   M.O
from analyze_me import db
from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from sqlalchemy.orm import relationship

#個人情報エントリ
class User(UserMixin, db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    user_id = db.Column(db.String(50), unique=True, nullable=False)
    name = db.Column(db.String(30), nullable=False)
    password = db.Column(db.String(20), unique=True, nullable=False)
    gender = db.Column(db.String(20), nullable=False)
    created_at = db.Column(db.DateTime)

    fu_results = relationship('FU_results')
    eq_results = relationship('EQ_results')
    ces_results = relationship('CES_results')
    pom_results = relationship('POM_results')
    teg_results = relationship('TEG_results')

    @classmethod
    def from_args(cls, user_id:str, name:str, password:str, gender:str):
        instance = cls()
        instance.user_id = user_id
        instance.name = name
        if password is not None:
            instance.hash_password(password)
        instance.gender = gender
        instance.created_at = datetime.utcnow()
        return instance

    def hash_password(self, clean_password):
        self.password = generate_password_hash(str(clean_password), method='sha256')

    def check_password(self, clean_password):
        return check_password_hash(self.password, clean_password)

    def __repr__(self):
        return '<Entry id:{} name:{} user_id:{}>'.format(self.id, self.name, self.user_id)

analyze_me/__init__.py
#analyze_me/__init__.py       2020/9/17   M.O
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

#sqlalchemyを通しflaskからdbへアクセスする入口
db = SQLAlchemy()

#app生成
def create_app(test_config=None):
    # Flaskアプリ生成
    app = Flask(__name__)

    #コンフィグ召喚
    app.config.from_object('analyze_me.config')

    #テストコンフィグ召喚
    if test_config:
        app.config.from_mapping(test_config)

    #アプリケーションとデータベースの紐付け
    db.init_app(app)

    # flask-loginに関する設定
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    # DBインポート
    from analyze_me.models.user import User
    from analyze_me.models.results import FU_results, EQ_results, \
        CES_results, POM_results, TEG_results

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    #blueprint（views）インポート
    from analyze_me.views.views import views
    app.register_blueprint(views)

    #blueprint（auth）インポート
    from analyze_me.views.auth import auth
    app.register_blueprint(auth)

    #blueprint（analyzes）インポート
    from analyze_me.views.analyzes import analyzes
    app.register_blueprint(analyzes, url_prefix='/analyzes')

    return app

analyze_me/views.py
#analyze_me/views.py       2020/9/17   M.O
from flask import request, redirect, url_for, \
    render_template, flash, session
from analyze_me import app

#トップページ
@app.route('/')
def index():
    return render_template('index.html')

#個人情報(過去log)ページ
@app.route('/log')
def show_entries():
    if not session.get('logged_in'):
        return redirect(url_for('login'))
    return render_template('entries/log.html')

#アナライザリスト
@app.route('/list')
def analyzer_list():
    return render_template('analyzer/list.html')

#アナライザ説明
@app.route('/description')
def description():
    return render_template('analyzer/description.html')

#アナライザ本体
@app.route('/analyzer')



#ログイン
@app.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':            #ログイン画面入力時
        if request.form['username'] != app.config['USERNAME']:
            flash('ユーザ名が異なります')
        elif request.form['password'] != app.config['PASSWORD']:
            flash('パスワードが異なります')
        else:
            session['logged_in'] = True
            flash('ログインしました')
            return redirect(url_for('show_entries'))
    return render_template('login.html')    #ログイン画面遷移時、入力エラー時

#ログアウト
@app.route('/logout')
def logout():
    session.pop('logged_in', None)
    flash('ログアウトしました')
    return redirect(url_for('index'))

analyze_me/views/analyzes.py
#analyze_me/analyzes.py       2020/10/07   M.O
#コンテンツ関連viewファイル
from flask import current_app as app
from flask import request, redirect, url_for, \
    render_template, flash, session
from flask import Blueprint
from flask_login import login_required, current_user
from analyze_me.services import analyzer_service

#ブループリント設定
analyzes = Blueprint('analyzes', __name__)

#アナライザリスト
@analyzes.route('/analyzers_list/')
def analyzer_list():
    analyzer_service.delete_param()
    return render_template('analyzer/list.html')


#説明
@analyzes.route('/description/<ex_id>')
def description(ex_id):
    analyzer_service.set_param(ex_id)
    ana = analyzer_service.setting_analyzer(session['ex_id'])
    return render_template('analyzer/description.html', ana=ana)


#テスト
@analyzes.route('/analyzer/<ex_id>', methods=['GET', 'POST'])
@login_required
def analyzer(ex_id):
    ana = analyzer_service.setting_analyzer(ex_id)
    if request.method == 'POST':
        try:
            ans = request.form.get('answer')
            ana.cal(int(ans))
            session['que'] += 1
            #print("ただいまの質問：{}".format(session['que']))
            #print("ANSWER：{}".format(session['answers']))
            #print("A_SUM: {}".format(session['a_sum']))
        except TypeError:
            flash('回答が選択されていません。')

        if session['que'] >= len(ana.queries):
            session['judge'] = ana.judge()
            result_id = analyzer_service.save()
            return redirect(url_for('views.result', ex_id=ex_id, result_id=result_id))
    return render_template('analyzer/query.html', ana=ana)

analyze_me/views/auth.py
#analyze_me/views/auth.py       2020/12/01   M.O
#ログイン関連用viewファイル
from flask import current_app as app
from flask import request, redirect, url_for, \
    render_template, flash, session, Blueprint
#from functools import wraps
from analyze_me.services import auth_service, analyzer_service

#ブループリント設定
auth = Blueprint('auth', __name__)

#ユーザデータ登録
@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    error = None
    if request.method == 'POST':            #ログイン画面入力時
        user, new_user = auth_service.signup(request.form)
        if user == 'empty':
            flash('未記入の項目があります')
            return render_template('auth/signup.html')
        elif user:
            flash('このユーザIDはすでに登録されています')
            return redirect(url_for('auth.login'))
        else:
            flash('新規登録に成功しました')
            #return redirect(url_for('auth.login'))
            return redirect(url_for('auth.confirm', \
                                    user_id = new_user.user_id, \
                                    user_name=new_user.name, \
                                    gender=new_user.gender))
    return render_template('auth/signup.html')    #サインアップ画面遷移時、入力エラー時


#登録データ確認
@auth.route('/confirm/<user_id>/<user_name>/<gender>', methods=['GET'])
def confirm(user_id, user_name, gender):
    return render_template('auth/confirm.html', user_id=user_id, \
                           user_name=user_name, gender=gender)


#ログイン
@auth.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':            #ログイン画面入力時
        user = auth_service.login(request.form)
        if user == 'empty':
            flash('未記入の項目があります')
            return render_template('auth/login.html')
        elif not user:
            flash('ユーザIDまたはパスワードに誤りがあります')
            return render_template('auth/login.html')
        else:
            #session['logged_in'] = True
            flash('ログインしました')
            return redirect(url_for('views.show_logs'))
    return render_template('auth/login.html')    #ログイン画面遷移時、入力エラー時

#ログアウト
@auth.route('/logout')
def logout():
    #session.pop('logged_in', None)
    auth_service.logout()
    analyzer_service.delete_param()
    flash('ログアウトしました')
    return redirect(url_for('views.index'))


#ログイン承認デレコーダ
"""
def login_required(view):
    @wraps(view)
    def inner(*args, **kwargs):
        if not session.get('logged_in'):
            return redirect(url_for('auth.login'))
        return view(*args, **kwargs)
    return inner
"""

analyze_me/views/views.py
#analyze_me/views.py       2020/9/17   M.O
#ログイン関連用viewファイル
from flask import current_app as app
from flask import request, redirect, url_for, \
    render_template, flash, session, Blueprint
from flask_login import login_required
from analyze_me.services import analyzer_service, \
    views_service, graph_service, desc_indivi_service

#ブループリント設定
views = Blueprint('views', __name__)

#トップページ
@views.route('/')
def index():
    return render_template('index.html')

#導入ページ
@views.route('/introduction/')
def intro():
    return render_template('intro.html')

#過去ログページ
@views.route('/logs/')
@login_required
def show_logs():
    fu_results = views_service.find_all('fu')
    eq_results = views_service.find_all('eq')
    ces_results = views_service.find_all('ces')
    pom_results = views_service.find_all('pom')
    teg_results = views_service.find_all('teg')
    ces_date, ces_asum = graph_service.ex_all_data('ces')   # ces-d graph
    fu_date, fu_asum = graph_service.ex_all_data('fu')      # fu graph
    eq_date, eq_asum = graph_service.ex_all_data('eq')      # eq graph
    return render_template('logs/logs.html', fu_results=fu_results, \
                           eq_results=eq_results, ces_results=ces_results, \
                           pom_results=pom_results, teg_results=teg_results, \
                           ces_date=ces_date, ces_asum=ces_asum, fu_date=fu_date, \
                           fu_asum=fu_asum, eq_date=eq_date, eq_asum=eq_asum)


#グラフ表示(log画面):未使用
@views.route('/logs/graph/')
def plot_graph():
    response = graph_service.draw_three_graphs()
    return response


#表示内容削除(log画面)＜通常非表示＞
@views.route('/result/delete/<ex_id>/<result_id>/', methods=['POST'])
@login_required
def delete_result(ex_id, result_id):
    views_service.delete(ex_id, result_id)
    flash('データを削除しました')
    return redirect(url_for('views.show_logs'))


#結果表示
@views.route('/result/<ex_id>/<result_id>/', methods=['GET'])
@login_required
def result(ex_id, result_id):
    ana = analyzer_service.setting_analyzer(ex_id)
    result = views_service.find_one(ex_id, result_id)

    if ex_id == 'pom' or ex_id == 'teg':
        g_fac, g_sum = graph_service.ex_one_data(ex_id, result_id)

        return render_template('logs/result_graph.html', \
                               ex_id=ex_id, result_id=result_id, \
                               ana=ana, result=result, g_fac=g_fac, g_sum=g_sum)
    else:
        return render_template('logs/result.html', \
                                ex_id=ex_id, result_id=result_id, \
                                ana=ana, result=result)


#TEG パラメータ説明
@views.route('/description_<ex_id>/<result_id>/')
def desc_teg(ex_id, result_id):
    if ex_id == "teg":
        desc = desc_indivi_service.Desc_teg()
    return render_template('logs/desc01_teg.html', ex_id=ex_id, result_id=result_id, desc=desc)


#グラフ表示(個別画面＿TEG, POMS):未使用
@views.route('/logs/graph/<ex_id>/<result_id>/')
def plot_graph_indivi(ex_id, result_id):
    response = graph_service.draw_graph(ex_id, result_id)
    return response

#404エラー時処理
@views.errorhandler(404)
def non_existant_route(error):
    return redirect(url_for('views.index'))

analyze_me/templates/index.html
<!-- analyze_me/templates/index.html 2020/09/23  M.O-->
{% extends "layout.html" %}
<!-- ヘッダー　-->
{% block head %}
    {{ super() }}
{% endblock %}

<!-- ボディ　-->
{% block body %}
<section class="indexA">
    <div>

        <img src="static/img/bottle.png" alt="">
        <h1>ANALyZE ME</h1>
        <a href="{{ url_for('views.intro') }}">START</a>

    </div>
</section>
{% endblock %}

analyze_me/templates/intro.html
<!-- analyze_me/templates/intro.html 2021/01/21  M.O-->
{% extends "layout.html" %}

<!-- ボディ　-->
{% block body %}
<section class="introA">
    <div class="con">

        <h2>Introduction</h2>
        <p>ようこそ！</p>
        <p class="symbol"><span class="far fa-gem"></span></p>
        <!--img src="static/img/bottle.png" alt=""-->

        <div class="conA">
        <h5>□︎□︎　ANALyZE ME とは？　□︎□︎︎</h5>
            <div class="conB">
                <ul>
                    <li>ANALyZE ME とは簡単は心理テストを行い、データを比較して自分の持つ傾向や、
                        時間経過による推移などを見ることができるWEBアプリケーションです。</li>
                    <li>ここでは、自分の心理状態を知るのに有効な以下５種類の心理テストを実施することができます。</li>
                    <li>　1. TEGエゴグラム</li>
                    <li>　　　自分の持つ自我状態の傾向（性格傾向）を確認するテストです。</li>
                    <li>　2. POMS</li>
                    <li>　　　自分の今現在の気分の状態を確認することができます。</li>
                    <li>　3. CES-D</li>
                    <li>　　　自分の現在のうつ的傾向を知ることができます。</li>
                    <li>　4. FU(フュージョン)チェック</li>
                    <li>　　　認知的フュージョン度を確認するテストです。</li>
                    <li>　5. EQ(脱中心化)チェック</li>
                    <li>　　　脱中心化尺度を確認するテストです。</li>
                    <LI>早速登録して始めてみましょう！</LI>
                </ul>
            </div>
        </div>
        <a href="{{ url_for('analyzes.analyzer_list') }}">アナライザリストへ</a>
    </div>
</section>
{% endblock %}

analyze_me/templates/layout.html
<!-- analyze_me/templates/layout.html 2020/02/23 M.O -->
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Analyze Me</title>
    {% block head %}
    <!-- スタイルシート指定 -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}">
    <!-- フォント設定_GoogleFonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Big+Shoulders+Stencil+Display:wght@300&display=swap" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    <script>
        $(function(){
            $(".headC").click(function(){
                $(".headB").slideToggle();
            });
        });

        $(function(){
            $(".alert").fadeOut(5000);
        });
    </script>

    {% endblock %}
</head>
<body>
<div><!-- div class="container" -->
    <!-- ヘッダー -->
    <header>
        <nav class="conH">
            <div class="conH-small">
                <a class="headA" href="{{ url_for('views.index') }}">ANALyZE ME</a>

                <button class="headC" type="button">
                    <span class="fas fa-bars" title="MENU"></span>
                </button>
            </div>
            <div class="headB">
                <ul>
                    <li>
                        <a href="{{ url_for('analyzes.analyzer_list') }}">リスト</a>
                    </li>

                    {% if not current_user.is_authenticated %}

                    <li>
                        <a href="{{ url_for('auth.login') }}">LOGIN</a>
                    </li>

                    {% else %}

                    <li>
                        <a href="{{ url_for('views.show_logs') }}"><span>{{ current_user.name }}さんの</span>過去ログ</a>
                    </li>

                    <li>
                        <a href="{{ url_for('auth.logout') }}">LOGOUT</a>
                    </li>

                    {% endif %}

                </ul>
            </div>
        </nav>

        <!-- flashメッセージ表示 -->
        {% for message in get_flashed_messages() %}
        <div class="alert alert-info" role="alert">
            {{ message }}
        </div>
        {% endfor %}

    </header>

    <!-- コンテンツ＿ページごとに異なる内容 -->
    {% block body %}{% endblock %}

    <!-- フッター -->
    <footer>

    </footer>
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<!--script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script-->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
</body>
</html>

analyze_me/templates/login.html
<!-- analyze_me/templates/login.html  2020/09/23  M.O-->
{% extends "layout.html" %}
{% block body %}

    <section class="loginA">
        <div class="container">

            <h2>LOGIN</h2>
            <p class="symbol"><span class="far fa-gem"></span></p>

            <form action="{{ url_for('login') }}" method=post>
                <!-- ユーザ名インプット -->
                <div class="form-group">
                    <label for="InputTitle">User Name</label>
                    <input type="text" class="form-control" id="InputTitle" name=username>
                </div>
                <!-- パスワードインプット -->
                <div class="form-group">
                    <label for="InputPassword">Password</label>
                    <input type="password" class="form-control" id="InputPassword" name=password>
                </div>
                <!-- ログインボタン -->
                <button type="submit" class="button">LOGIN</button>
                <!--button-- type="submit" class="btn btn-primary">LOGIN</button-->
            </form>

        </div>
    </section>

{% endblock %}