analyze_me/models/results.py
#analyze_me/models/results.py       2020/12/10   M.O
from analyze_me import db
from datetime import datetime
#from sqlalchemy.dialects import postgresql as pg

#フュージョンチェックデータベース
class FU_results(db.Model):
    __tablename__ = 'fu_results'
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    answers = db.Column(db.PickleType, nullable=True)
    #answers = db.Column(pg.ARRAY(db.String, dimensions=1), nullable=True)
    a_sum = db.Column(db.Integer, nullable=True)
    judge = db.Column(db.String(200), nullable=True)
    created_at = db.Column(db.DateTime)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', onupdate='CASCADE', ondelete='CASCADE'), nullable=False)

    @classmethod
    def from_args(cls, answers: [], a_sum: int, judge: str, user_id: int) -> object:
        instance = cls()
        instance.answers = answers
        instance.a_sum = a_sum
        instance.judge = judge
        instance.created_at = datetime.now()
        instance.user_id = user_id
        return instance

    def __repr__(self):
        return '<ID:{} answers:{} judge:{}>'.format(self.id, self.answers, self.judge)


#脱中心化チェックデータベース
class EQ_results(db.Model):
    __tablename__ = 'eq_results'
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    answers = db.Column(db.PickleType, nullable=True)
    a_sum = db.Column(db.Integer, nullable=True)
    judge = db.Column(db.String(200), nullable=True)
    created_at = db.Column(db.DateTime)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', onupdate='CASCADE', ondelete='CASCADE'), nullable=False)

    @classmethod
    def from_args(cls, answers: [], a_sum: int, judge: str, user_id: int) -> object:
        instance = cls()
        instance.answers = answers
        instance.a_sum = a_sum
        instance.judge = judge
        instance.created_at = datetime.now()
        instance.user_id = user_id
        return instance

    def __repr__(self):
        return '<ID:{} answers:{} judge:{}>'.format(self.id, self.answers, self.judge)


# CES-Dデータベース
class CES_results(db.Model):
    __tablename__ = 'ces_results'
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    answers = db.Column(db.PickleType, nullable=True)
    a_sum = db.Column(db.Integer, nullable=True)
    judge = db.Column(db.String(200), nullable=True)
    created_at = db.Column(db.DateTime)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', onupdate='CASCADE', ondelete='CASCADE'), nullable=False)

    @classmethod
    def from_args(cls, answers: [], a_sum: int, judge: str, user_id: int) -> object:
        instance = cls()
        instance.answers = answers
        instance.a_sum = a_sum
        instance.judge = judge
        instance.created_at = datetime.now()
        instance.user_id = user_id
        return instance

    def __repr__(self):
        return '<ID:{} answers:{} judge:{}>'.format(self.id, self.answers, self.judge)


#　POMSデータベース
class POM_results(db.Model):
    __tablename__ = 'pom_results'
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    answers = db.Column(db.PickleType, nullable=True)
    a_sum = db.Column(db.PickleType, nullable=True)
    #judge = db.Column(db.String(200), nullable=True)
    created_at = db.Column(db.DateTime)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', onupdate='CASCADE', ondelete='CASCADE'), nullable=False)

    @classmethod
    def from_args(cls, answers: [], a_sum: [], user_id: int) -> object:
        instance = cls()
        instance.answers = answers
        instance.a_sum = a_sum
        #instance.judge = judge
        instance.created_at = datetime.now()
        instance.user_id = user_id
        return instance

    def __repr__(self):
        return '<ID:{} answers:{} judge:{}>'.format(self.id, self.answers, self.a_sum)


#　TEGデータベース
class TEG_results(db.Model):
    __tablename__ = 'teg_results'
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    answers = db.Column(db.PickleType, nullable=True)
    a_sum = db.Column(db.PickleType, nullable=True)
    #judge = db.Column(db.String(200), nullable=True)
    created_at = db.Column(db.DateTime)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', onupdate='CASCADE', ondelete='CASCADE'), nullable=False)

    @classmethod
    def from_args(cls, answers: [], a_sum: [], user_id: int) -> object:
        instance = cls()
        instance.answers = answers
        instance.a_sum = a_sum
        #instance.judge = judge
        instance.created_at = datetime.now()
        instance.user_id = user_id
        return instance

    def __repr__(self):
        return '<ID:{} answers:{} judge:{}>'.format(self.id, self.answers, self.a_sum)

analyze_me/models/user.py
#analyze_me/models/user.py       2020/11/30   M.O
from analyze_me import db
from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from sqlalchemy.orm import relationship

#個人情報エントリ
class User(UserMixin, db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    user_id = db.Column(db.String(50), unique=True, nullable=False)
    name = db.Column(db.String(30), nullable=False)
    password = db.Column(db.String(20), unique=True, nullable=False)
    gender = db.Column(db.String(20), nullable=False)
    created_at = db.Column(db.DateTime)

    fu_results = relationship('FU_results')
    eq_results = relationship('EQ_results')
    ces_results = relationship('CES_results')
    pom_results = relationship('POM_results')
    teg_results = relationship('TEG_results')

    @classmethod
    def from_args(cls, user_id:str, name:str, password:str, gender:str):
        instance = cls()
        instance.user_id = user_id
        instance.name = name
        if password is not None:
            instance.hash_password(password)
        instance.gender = gender
        instance.created_at = datetime.utcnow()
        return instance

    def hash_password(self, clean_password):
        self.password = generate_password_hash(str(clean_password), method='sha256')

    def check_password(self, clean_password):
        return check_password_hash(self.password, clean_password)

    def __repr__(self):
        return '<Entry id:{} name:{} user_id:{}>'.format(self.id, self.name, self.user_id)

analyze_me/__init__.py
#analyze_me/__init__.py       2020/9/17   M.O
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

#sqlalchemyを通しflaskからdbへアクセスする入口
db = SQLAlchemy()

#app生成
def create_app(test_config=None):
    # Flaskアプリ生成
    app = Flask(__name__)

    #コンフィグ召喚
    app.config.from_object('analyze_me.config')

    #テストコンフィグ召喚
    if test_config:
        app.config.from_mapping(test_config)

    #アプリケーションとデータベースの紐付け
    db.init_app(app)

    # flask-loginに関する設定
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    # DBインポート
    from analyze_me.models.user import User
    from analyze_me.models.results import FU_results, EQ_results, \
        CES_results, POM_results, TEG_results

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    #blueprint（views）インポート
    from analyze_me.views.views import views
    app.register_blueprint(views)

    #blueprint（auth）インポート
    from analyze_me.views.auth import auth
    app.register_blueprint(auth)

    #blueprint（analyzes）インポート
    from analyze_me.views.analyzes import analyzes
    app.register_blueprint(analyzes, url_prefix='/analyzes')

    return app

analyze_me/views.py
#analyze_me/views.py       2020/9/17   M.O
from flask import request, redirect, url_for, \
    render_template, flash, session
from analyze_me import app

#トップページ
@app.route('/')
def index():
    return render_template('index.html')

#個人情報(過去log)ページ
@app.route('/log')
def show_entries():
    if not session.get('logged_in'):
        return redirect(url_for('login'))
    return render_template('entries/log.html')

#アナライザリスト
@app.route('/list')
def analyzer_list():
    return render_template('analyzer/list.html')

#アナライザ説明
@app.route('/description')
def description():
    return render_template('analyzer/description.html')

#アナライザ本体
@app.route('/analyzer')



#ログイン
@app.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':            #ログイン画面入力時
        if request.form['username'] != app.config['USERNAME']:
            flash('ユーザ名が異なります')
        elif request.form['password'] != app.config['PASSWORD']:
            flash('パスワードが異なります')
        else:
            session['logged_in'] = True
            flash('ログインしました')
            return redirect(url_for('show_entries'))
    return render_template('login.html')    #ログイン画面遷移時、入力エラー時

#ログアウト
@app.route('/logout')
def logout():
    session.pop('logged_in', None)
    flash('ログアウトしました')
    return redirect(url_for('index'))

analyze_me/views/analyzes.py
#analyze_me/analyzes.py       2020/10/07   M.O
#コンテンツ関連viewファイル
from flask import current_app as app
from flask import request, redirect, url_for, \
    render_template, flash, session
from flask import Blueprint
from flask_login import login_required, current_user
from analyze_me.services import analyzer_service

#ブループリント設定
analyzes = Blueprint('analyzes', __name__)

#アナライザリスト
@analyzes.route('/analyzers_list/')
def analyzer_list():
    analyzer_service.delete_param()
    return render_template('analyzer/list.html')


#説明
@analyzes.route('/description/<ex_id>')
def description(ex_id):
    analyzer_service.set_param(ex_id)
    ana = analyzer_service.setting_analyzer(session['ex_id'])
    return render_template('analyzer/description.html', ana=ana)


#テスト
@analyzes.route('/analyzer/<ex_id>', methods=['GET', 'POST'])
@login_required
def analyzer(ex_id):
    ana = analyzer_service.setting_analyzer(ex_id)
    if request.method == 'POST':
        try:
            ans = request.form.get('answer')
            ana.cal(int(ans))
            session['que'] += 1
            #print("ただいまの質問：{}".format(session['que']))
            #print("ANSWER：{}".format(session['answers']))
            #print("A_SUM: {}".format(session['a_sum']))
        except TypeError:
            flash('回答が選択されていません。')

        if session['que'] >= len(ana.queries):
            session['judge'] = ana.judge()
            result_id = analyzer_service.save()
            return redirect(url_for('views.result', ex_id=ex_id, result_id=result_id))
    return render_template('analyzer/query.html', ana=ana)

analyze_me/views/auth.py
#analyze_me/views/auth.py       2020/12/01   M.O
#ログイン関連用viewファイル
from flask import current_app as app
from flask import request, redirect, url_for, \
    render_template, flash, session, Blueprint
#from functools import wraps
from analyze_me.services import auth_service, analyzer_service

#ブループリント設定
auth = Blueprint('auth', __name__)

#ユーザデータ登録
@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    error = None
    if request.method == 'POST':            #ログイン画面入力時
        user, new_user = auth_service.signup(request.form)
        if user == 'empty':
            flash('未記入の項目があります')
            return render_template('auth/signup.html')
        elif user:
            flash('このユーザIDはすでに登録されています')
            return redirect(url_for('auth.login'))
        else:
            flash('新規登録に成功しました')
            #return redirect(url_for('auth.login'))
            return redirect(url_for('auth.confirm', \
                                    user_id = new_user.user_id, \
                                    user_name=new_user.name, \
                                    gender=new_user.gender))
    return render_template('auth/signup.html')    #サインアップ画面遷移時、入力エラー時


#登録データ確認
@auth.route('/confirm/<user_id>/<user_name>/<gender>', methods=['GET'])
def confirm(user_id, user_name, gender):
    return render_template('auth/confirm.html', user_id=user_id, \
                           user_name=user_name, gender=gender)


#ログイン
@auth.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':            #ログイン画面入力時
        user = auth_service.login(request.form)
        if user == 'empty':
            flash('未記入の項目があります')
            return render_template('auth/login.html')
        elif not user:
            flash('ユーザIDまたはパスワードに誤りがあります')
            return render_template('auth/login.html')
        else:
            #session['logged_in'] = True
            flash('ログインしました')
            return redirect(url_for('views.show_logs'))
    return render_template('auth/login.html')    #ログイン画面遷移時、入力エラー時

#ログアウト
@auth.route('/logout')
def logout():
    #session.pop('logged_in', None)
    auth_service.logout()
    analyzer_service.delete_param()
    flash('ログアウトしました')
    return redirect(url_for('views.index'))


#ログイン承認デレコーダ
"""
def login_required(view):
    @wraps(view)
    def inner(*args, **kwargs):
        if not session.get('logged_in'):
            return redirect(url_for('auth.login'))
        return view(*args, **kwargs)
    return inner
"""

analyze_me/views/views.py
#analyze_me/views.py       2020/9/17   M.O
#ログイン関連用viewファイル
from flask import current_app as app
from flask import request, redirect, url_for, \
    render_template, flash, session, Blueprint
from flask_login import login_required
from analyze_me.services import analyzer_service, \
    views_service, graph_service, desc_indivi_service

#ブループリント設定
views = Blueprint('views', __name__)

#トップページ
@views.route('/')
def index():
    return render_template('index.html')

#導入ページ
@views.route('/introduction/')
def intro():
    return render_template('intro.html')

#過去ログページ
@views.route('/logs/')
@login_required
def show_logs():
    fu_results = views_service.find_all('fu')
    eq_results = views_service.find_all('eq')
    ces_results = views_service.find_all('ces')
    pom_results = views_service.find_all('pom')
    teg_results = views_service.find_all('teg')
    ces_date, ces_asum = graph_service.ex_all_data('ces')   # ces-d graph
    fu_date, fu_asum = graph_service.ex_all_data('fu')      # fu graph
    eq_date, eq_asum = graph_service.ex_all_data('eq')      # eq graph
    return render_template('logs/logs.html', fu_results=fu_results, \
                           eq_results=eq_results, ces_results=ces_results, \
                           pom_results=pom_results, teg_results=teg_results, \
                           ces_date=ces_date, ces_asum=ces_asum, fu_date=fu_date, \
                           fu_asum=fu_asum, eq_date=eq_date, eq_asum=eq_asum)


#グラフ表示(log画面):未使用
@views.route('/logs/graph/')
def plot_graph():
    response = graph_service.draw_three_graphs()
    return response


#表示内容削除(log画面)＜通常非表示＞
@views.route('/result/delete/<ex_id>/<result_id>/', methods=['POST'])
@login_required
def delete_result(ex_id, result_id):
    views_service.delete(ex_id, result_id)
    flash('データを削除しました')
    return redirect(url_for('views.show_logs'))


#結果表示
@views.route('/result/<ex_id>/<result_id>/', methods=['GET'])
@login_required
def result(ex_id, result_id):
    ana = analyzer_service.setting_analyzer(ex_id)
    result = views_service.find_one(ex_id, result_id)

    if ex_id == 'pom' or ex_id == 'teg':
        g_fac, g_sum = graph_service.ex_one_data(ex_id, result_id)

        return render_template('logs/result_graph.html', \
                               ex_id=ex_id, result_id=result_id, \
                               ana=ana, result=result, g_fac=g_fac, g_sum=g_sum)
    else:
        return render_template('logs/result.html', \
                                ex_id=ex_id, result_id=result_id, \
                                ana=ana, result=result)


#TEG パラメータ説明
@views.route('/description_<ex_id>/<result_id>/')
def desc_teg(ex_id, result_id):
    if ex_id == "teg":
        desc = desc_indivi_service.Desc_teg()
    return render_template('logs/desc01_teg.html', ex_id=ex_id, result_id=result_id, desc=desc)


#グラフ表示(個別画面＿TEG, POMS):未使用
@views.route('/logs/graph/<ex_id>/<result_id>/')
def plot_graph_indivi(ex_id, result_id):
    response = graph_service.draw_graph(ex_id, result_id)
    return response

#404エラー時処理
@views.errorhandler(404)
def non_existant_route(error):
    return redirect(url_for('views.index'))

analyze_me/templates/analyzer/description.html
<!-- analyze_me/templates/analyzer/description.html 2020/10/07  M.O-->
{% extends "layout.html" %}
{% block body %}

<section class="descA">
    <div class="con">

        <h2>{{ ana.name }}</h2>
        <h5>{{ ana.sub }}</h5>
        <p class="symbol"><span class="far fa-gem"></span></p>

        <div class="conA">
        <h5>□︎□︎　説明　□︎□︎︎</h5>
            <div class="conB">
                <ul>
                    {% for desc in ana.desc %}
                    <li>
                        {{ desc }}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <a href="{{ url_for('analyzes.analyzer', ex_id=session.ex_id) }}">テストを始める</a>
        <a href="{{ url_for('analyzes.analyzer_list') }}" class="list-btn">アナライザリストに戻る</a>
    </div>
</section>

{% endblock %}

analyze_me/templates/analyzer/list.html
<!-- analyze_me/templates/analyzer/.html 2020/10/6  M.O-->
{% extends "layout.html" %}
{% block body %}

<section class="listA">
    <div class="con">

        <h2>LIST of ANALyZERS</h2>
        <p>実施するテストを選ぶと解説ページに移動します</p>
        <p class="symbol"><span class="far fa-gem"></span></p>

        <div class="conA">
        <ul>
            <li>
                <a class="ele" href="{{ url_for('analyzes.description', ex_id='teg') }}" >TEGエゴグラム</a>
            </li>
            <li>
                <a class="ele" href="{{ url_for('analyzes.description', ex_id='pom') }}" >POMS</a>
            </li>
            <li>
                <a class="ele" href= "{{ url_for('analyzes.description', ex_id='ces') }}" >CES-D</a>
            </li>
            <li>
                <a class="ele" href="{{ url_for('analyzes.description', ex_id='fu') }}" >FUチェック</a>
            </li>
            <li>
                <a class="ele" href="{{ url_for('analyzes.description', ex_id='eq') }}"  >EQチェック</a>
            </li>
        </ul>
        </div>

        {% if not current_user.is_authenticated %}
        <p class="p1">未登録の方は
                <span>
                    <a href="{{ url_for('auth.signup') }}">ユーザー登録</a>
                </span>
                してください
        </p>
        {% endif %}

    </div>
</section>

{% endblock %}

analyze_me/templates/analyzer/query.html
<!-- analyze_me/templates/analyzer/query.html 2020/10/06  M.O-->
{% extends "layout.html" %}
{% block body %}

<section class="queA">
    <div class="con">

        <h2>{{ ana.name }}</h2>
        <p class="symbol"><span class="far fa-gem"></span></p>

        <div class="conA">
        <h5>□︎□︎　質問{{ session.que+1 }}　□︎□︎</h5>
        <p class="quest">{{ ana.queries[session.que] }}</p>

        <form action="{{ url_for('analyzes.analyzer', ex_id=session.ex_id ) }}" method="POST">
            {% for opt in range(0, ana.options|length) %}
            <input class="radio" type="radio" name="answer" id={{ opt }} value={{ opt }} >
            <label class="label" for={{ opt }} >{{ ana.options[opt] }}</label>
            <br>
            {% endfor %}
            <input class="button" type="submit" value="決定">
        </form>
        </div>

    </div>
</section>

{% endblock %}

analyze_me/templates/analyzer/result.html
<!-- analyze_me/templates/analyzer/result.html 2020/11/03  M.O-->
{% extends "layout.html" %}
{% block body %}

<section class="resA">
    <div class="con">

        <h2>{{ ana.name }}</h2>
        <p class="symbol"><span class="far fa-gem"></span></p>

        <h5>判定</h5>
        <p>{{ result.judge }}</p>

        <table border="1">
            <tr>
                <th>No.</th>
                <th>質問</th>
                <th>回答</th>
            </tr>
            {% for que in range(0, ana.queries|length) %}
            <tr>
                <td>{{ que+1 }}</td>
                <td>{{ ana.queries[que] }}</td>
                <td>{{ result.answers[que] }}</td>
            </tr>
            {% endfor %}
        </table>

        <a href="{{ url_for('analyzes.analyzer_list') }}">リストに戻る</a>

    </div>
</section>

{% endblock %}

analyze_me/templates/analyzer/result_graph.html
<!-- analyze_me/templates/analyzer/result_graph.html 2020/11/06  M.O-->
{% extends "layout.html" %}
{% block body %}

<section class="resB">
    <div class="con">

        <h2>{{ ana.name }}</h2>
        <p class="symbol"><span class="far fa-gem"></span></p>

        <h5>結果</h5>
        <table class="tabA">
            <tr>
                {% for f in range(0, result.a_sum|length) %}
                    <td class="tdA">{{ ana.fac[f] }}</td>
                    <td>{{ result.a_sum[f] }}</td>
                {% endfor %}
            </tr>
        </table>

        <table class="tabB" border="1">
            <tr>
                <th>No.</th>
                <th>質問</th>
                <th>回答</th>
            </tr>
            {% for que in range(0, ana.queries|length) %}
            <tr>
                <td>{{ que+1 }}</td>
                <td>{{ ana.queries[que] }}</td>
                <td>{{ result.answers[que] }}</td>
            </tr>
            {% endfor %}
        </table>

        <a href="{{ url_for('analyzes.analyzer_list') }}">リストに戻る</a>

    </div>
</section>

{% endblock %}